source 'https://github.com/afilipowicz/ModifiedPodsSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'SVPullToRefresh_Tests', :exclusive => true do
  pod 'SVPullToRefresh', :path => '../'
  
end
